### PR TITLE
Elided code that caused ctrl keyboard shortcuts to fail on 32b images

### PR DESCRIPTION
**Pull request by kksubbu**
This patch solves the problem discussed in https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/396

### CODE REVIEW

**Comment by krono** [comment]
I think we really should wait with this until Eliot's approval. He put the code in there not too long ago, and I'm sure he had good reason to…

**Comment by nicolas-cellier-aka-nice** [comment]
I agree with Tobias, I suggest that we analyze the failure further, specifically what happens to modifiers state before reverting those lines. I commented Issue #396 with a bit more information about my yet incomplete understanding of the problem.

**Comment by eliotmiranda** [comment]
On Sun, Jun 9, 2019 at 8:33 AM Tobias Pape <notifications@github.com> wrote:

> I think we really should wait with this until Eliot's approval. He put the
> code in there not too long ago, and I'm sure he had good reason to…
>

IIRC, I just rubber stamped someone else's contribution.

_,,,^..^,,,_
best, Eliot

**Comment by akgrant43** [comment]
I think this is the relevant issue: https://github.com/feenkcom/gtoolkit/issues/9#issuecomment-447487311
See John Brant's comments from 14 December.

**Comment by bencoman** [comment]
Good find @akgrant43. Paraphrasing feenkcom/gtoolkit#9...

[Edit: ] Better to record this on the issue... https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/396#issuecomment-501308271

**Comment by kksubbu** [comment]
John Brant reported that this patch breaks ctrl-a handling in 64b image. So this patch will not solve the issue for all Squeak and Pharo images. I will withdraw the patch. Further discussions can continue in #396

**Pull request closed without merging**
