### PR TITLE
21234-Add-FileAttributesPlugin-to-win64x64

### PR DESCRIPTION
**Pull request by akgrant43**
Add FileAttributesPlugin to build.win64x64/pharo.cog.spur/plugins.ext

All pharo.cog.spur platforms are now compiling FileAttributesPlugin.

### CODE REVIEW

**Comment by akgrant43** [comment]
Fogbugz: https://pharo.fogbugz.com/f/cases/21234/Add-FileAttributesPlugin-to-win64x64

**Comment by akgrant43** [comment]
win64x64 appears to be incorrectly trying to use lstat() (win32 does the right thing).  I'll have to look in to this further.

Cheers,
Alistair

**Comment by fniephaus** [comment]
Please note that third party libs for Pharo are also failing to build on macOS at the moment.

**Comment by akgrant43** [comment]
Currently working on the solution, see: http://lists.squeakfoundation.org/pipermail/vm-dev/2018-February/026715.html

**Comment by akgrant43** [comment]
The CI build failed, however it appears to be a problem with uploading the files at the end (ssh connection reset).

I've marked the fogbugz issue Resolved (Fix Review Needed)

**Comment by fniephaus** [comment]
@eliotmiranda can this be merged?

**Comment by akgrant43** [comment]
Note that FileAttributesPlugin.c is generated from:

Name: FileAttributesPlugin.oscog-AlistairGrant.27
Author: AlistairGrant
Time: 16 February 2018, 2:50:37.845172 pm
UUID: 5f8d8c2b-5326-4d03-80d3-348e0a109592
Ancestors: FileAttributesPlugin.oscog-AlistairGrant.26

**Pull request merged**
