### PR TITLE
Fix include order

### PR DESCRIPTION
**Pull request by nicolas-cellier-aka-nice**
This enables the linux builds again, while preserving windows and macos builds.
That is a fix for https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/560

If this is compatible with TERF VM, then it should be merged ASAP, the builds are red for too long.
(we'll have to inquire next point of failure...)

### CODE REVIEW

**Review by fniephaus — APPROVED** [review]
LGTM, don't know about TERF. Thanks, @nicolas-cellier-aka-nice!

**Review by marceltaeumel — APPROVED** [review]
Maybe merge the current upstream again. Please make the Linux builds work again. Thanks Nicolas!

**Comment by dtlewis290** [comment]
This issue apparently affects (some?) Windows builds in addition to unix, see issue #568

**Comment by smalltalking** [comment]
We definitely need this asap.

**Comment by marceltaeumel** [comment]
So, I updated this PR to HEAD. I will merge this soon. Just testing MSVC builds now.

Some remaining quirks (using VMMaker.oscog-mt.2986 in VMMakerInbox, based in -nice.2957, also in inbox) are:
- "#include <asm/cachectl.h>" moves to the bottom in cogitMIPSEL.c
- Some hiccups (and extra type casts) regarding usqInt vs sqInt ... ? Maybe it is nothing, maybe there is some extra magic here during source generation that I am not aware of.

So, besides that include-order thingy in the VMMaker, there are only those extra HAVE_CONFIG_H in cross-platform sources:
platforms/Cross/plugins/B3DAcceleratorPlugin/sqOpenGLRenderer.c 
platforms/Cross/plugins/IA32ABI/xabicc.c
platforms/Cross/plugins/SoundCodecPrims/sqSoundCodecPluginBasicPrims.c
platforms/Cross/plugins/Squeak3D/b3dInit.c 
platforms/Cross/plugins/Squeak3D/b3dMain.c
platforms/Cross/plugins/SurfacePlugin/SurfacePlugin.c
platforms/Cross/vm/sqHeapMap.c
platforms/Cross/vm/sqVirtualMachine.c 

Platform-specific fixes considering HAVE_CONFIG_H:
platforms/unix/plugins/FileAttributesPlugin/faSupport.c 
platforms/unix/vm/aio.c 
platforms/unix/vm/sqUnixVMProfile.c 
platforms/win32/vm/sqPlatformSpecific.h 

And this:
platforms/unix/config/getversion.c
platforms/Cross/vm/sqSCCSVersion.h
platforms/Cross/vm/sqAssert.h

**Comment by marceltaeumel** [comment]
Note that sources have to be generated even if a dialog claims that there are not changes. Apparently, the order of include files is not considered a change in the generated artifact:

```Smalltalk
[VMMaker generateAllConfigurationsUnderVersionControl] valueSupplyingAnswer: true. "Not false!"
```

Also note that the current VMMaker changes are in the VMMakerInbox:
- VMMaker.oscog-mt.2986 based on
- VMMaker.oscog-dtl.2968 based on
- VMMaker.oscog-nice.2957

**Review by eliotmiranda — APPROVED** [review]
Looks fine to me.  Clearly we need to regenerate sources. Deep apologies for having dragged my feet on this.  A long dark night of the soul, now happily in the past (echo cancellation).

**Comment by krono** [comment]
Thanks a bunch :D

**Comment by KenDickey** [comment]
Builds on aarch64/arm64 Linux work fine.
Build order still a problem on build.linux32ARMv6/squeak.cog.spur/build
[Tested on Raspberry Pi 3 on RasPi Linux].
Still have to comment out  #ifdef _FEATURES_H in "config.h" as workaround

**Comment by marceltaeumel** [comment]
> Build order still a problem on build.linux32ARMv6/squeak.cog.spur/build
> [Tested on Raspberry Pi 3 on RasPi Linux].
> Still have to comment out #ifdef _FEATURES_H in "config.h" as workaround

So, the build.linux32ARMv6 config does include "features.h" before "config.h" but that's not an issue for ARMv6? How come?

The only unix-specific changes were in these files:
- platforms/unix/plugins/FileAttributesPlugin/faSupport.c
- platforms/unix/vm/aio.c
- platforms/unix/vm/sqUnixVMProfile.c

Don't those apply to the ARMv6 build as well? Would you post the details where "features.h" is included first?

**Comment by KenDickey** [comment]
On 2021-07-25 23:32, Marcel Taeumel wrote:

>>  Would you post the details where "features.h" is included first?

OK.  I captured the entire trace, but I believe the salient section is:

vvv===vvv
gcc -Wall   -g -O2 -DNDEBUG -DDEBUGVM=0 -D_GNU_SOURCE -DUSEEVDEV 
-DI_REALLY_DONT_CARE_HOW_UNSAFE_THIS_IS -DUSE_MIDI_ALSA -DCOGMTVM=0 
-pthread -DLSB_FIRST=1 -march=armv6 -mfpu=vfp -mfloat-abi=hard 
-Wno-missing-braces -Wno-unknown-pragmas -Wno-unused-value 
-Wno-unused-label -Wno-unused-function -Wno-unused-variable 
-Wno-unused-but-set-variable -DENABLE_FAST_BLT -DHAVE_CONFIG_H  
-DSQUEAK_BUILTIN_PLUGIN 
-I/home/pi/OpenSmalltalk/kenVMfix/build.linux32ARMv6/squeak.cog.spur/build 
-I/home/pi/OpenSmalltalk/kenVMfix/build.linux32ARMv6/squeak.cog.spur/build 
-I/home/pi/OpenSmalltalk/kenVMfix/platforms/unix/vm 
-I/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/vm 
-I/home/pi/OpenSmalltalk/kenVMfix/spursrc/vm -I/usr/local/include 
-I/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/plugins/BitBltPlugin  
-march=armv6 -mfpu=vfp -mfloat-abi=hard -Wno-missing-braces 
-Wno-unknown-pragmas -Wno-unused-value -Wno-unused-label 
-Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable   
-c -o BitBltArmSimd.o 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/plugins/BitBltPlugin/BitBltArmSimd.c
In file included from 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/vm/sqMemoryAccess.h:23,
                  from 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/vm/sqVirtualMachine.h:30,
                  from 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/plugins/BitBltPlugin/BitBltDispatch.h:30,
                  from 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/plugins/BitBltPlugin/BitBltInternal.h:29,
                  from 
/home/pi/OpenSmalltalk/kenVMfix/platforms/Cross/plugins/BitBltPlugin/BitBltArmSimd.c:29:
/home/pi/OpenSmalltalk/kenVMfix/build.linux32ARMv6/squeak.cog.spur/build/config.h:40:2: 
error: #error This file was included too late. Please make sure it is 
included earlier
  #error This file was included too late. Please make sure it is included 
earlier
   ^~~~~
make[1]: *** [Makefile:182: BitBltArmSimd.o] Error 1
make: *** [Makefile:426: BitBltPlugin/BitBltPlugin.a] Error 2
make: *** Waiting for unfinished jobs....
^^^===^^^

**Comment by KenDickey** [comment]
Did a mvm build on RasPi3: build.kinux32ArmV6/squeak.cog.spur/build.

Changed "mvm" to add flag "-DUSEEVDEV", after which vm-display-fbdev built and VM runnable.  

The -DUSEEVDEV flag should be set based on current pull request for fixes to vm-display-fbdev.

**Comment by krono** [comment]
Ah I remember. ARM32 has a custom BitBlt-Plugin.

Did 06d1b2d208b64b534eff81d8bb51a4abd8c2146d fix it?

**Comment by KenDickey** [comment]
Looks good now.

Thanks much!

**Pull request merged**
