### PR TITLE
Make Pharo use "standard" sources (spursrc, spur64src and src/plugins) 

### PR DESCRIPTION
**Pull request by estebanlm**
2nd attempt :)
(eventually I will finish all this integrations and PRs will be smaller)

- best than needing a regeneration each time (for osvm... we still make the generation but we don't care :P)
- so we can remove (and we do it) `pharosrc` and `pharo64src`

### CODE REVIEW

**Comment by nicolas-cellier-aka-nice** [comment]
As a rule of thumb, if ever github interface displays
"Sorry, we could not display the entire diff because it was too big. "
then a review of the changes will hardly be possible at all

**Comment by estebanlm** [comment]
I know, but here is not necessary. 
I just removed pharosrc/pharo64src and generate sources from VMMaker

(and redirect makefiles to here)

no need to review anything :)

Esteban

**Comment by nicolas-cellier-aka-nice** [comment]
OK, A=Added D=Deleted M=Modified, it's just that I don't know what the I status mean?

**Comment by eliotmiranda** [comment]
Great news, Esteban.  Thanks!!

On Wed, Sep 21, 2016 at 5:24 AM, Esteban Lorenzano <notifications@github.com
> wrote:

> 2nd attempt :)
> (eventually I will finish all this integrations and PRs will be smaller)
>
>    - best than needing a regeneration each time (for osvm... we still
>    make the generation but we don't care :P)
>    - so we can remove (and we do it) pharosrc and pharo64src
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/58
> Commit Summary

 [snip]
-- 
_,,,^..^,,,_
best, Eliot

**Pull request merged**
