### PR TITLE
Pullrequest2/vmmaker

### PR DESCRIPTION
**Pull request by georgeganea**
Since the previous pullrequest (pullrequest/vmmaker) was not updated with the new commits, I'm opening a new one. 
In this episode: 
- commit comments also contain the mcz filename 
- the category issue has beed addressed 
- the commit dates and author dates are now the same so that the Github Network insight view is usable again

### CODE REVIEW

**Comment by bencoman** [comment]
Greatly appreciate the fix to the commit dates.   The network graph looks much better. Thx George.
Its good to have the mcz name there too, but its a bit opaque having "only" the mcz name.  
So a suggestion to fine-tune that... merge the first three lines of the mcz-commit-message onto a single line for the git-commit-message.  As shown here, only the first line of the commit message is displayed...
vmmaker-extra-comment

You should be able to reproduce that by doing...
```
$ git remote add ben  https://github.com/bencoman/opensmalltalk-vm.git
$ git fetch ben
$ git checkout -b ben/vmmaker-unmerged   # taken from this pull request
$ git branch vmmaker-comment-mod
$ git checkout vmmaker-comment-mod
$ git filter-branch -f --msg-filter /your/path/to/vmmaker-comment-mod.awk
````
where **vmmaker-comment-mod.awk** is...
```
#!/usr/bin/awk -f
(NR==1) {printf "%s.mcz ", $0 ; next}
(NR==2) {printf "%s ", $0; next}
{print}
```
Adding the ".mcz" will make vmmaker more explicit after merging into the Cog mainline.

**Comment by bencoman** [comment]
btw, I'm curious how the merge into the Cog branch is done.  You can see in the graph the red line dropping down from the **OpenSmalltalk/Cog** branch to join the blue line from **bencoman/vmmaker-comment-mod** branch.  This was produced by doing...
```
$ git remote add OpenSmalltalk  https://github.com/OpenSmalltalk/opensmalltalk-vm.git
$ git fetch OpenSmalltalk
$ git branch vmmaker-merge
$ git checkout vmmaker-merge
$ git merge OpenSmalltalk/Cog --allow-unrelated-histories
```

but you must be doing something different (perhaps outside git)
since I don't see any merge line from Cog into this pull request.

**Comment by georgeganea** [comment]
The merge into Cog should be done once the pull request is accepted. In your fork, you merged OpenSmalltalk/Cog into the vmmaker branch. That is why that blue line is there. I did not do that last step you did: `git merge OpenSmalltalk/Cog --allow-unrelated-histories`.

I'm not sure I understand if/why we need to merge OpenSmalltalk/Cog into feenkcom/pullrequest3/vmmaker before we merge feenkcom/pullrequest3/vmmaker into OpenSmalltalk/Cog.

**Comment by georgeganea** [comment]
I've deleted pullrequest2 and created https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/309.

**Comment by bencoman** [comment]
> I did not do that last step you did: ```git merge OpenSmalltalk/Cog --allow-unrelated-histories.```

But on that branch your last commit was "merge with Cog" and ```git log```  seemed to show history items from the Cog branch, and I couldn't guess how you did it.  Just asking to see if I could learn something new.

> I'm not sure I understand if/why we need to merge OpenSmalltalk/Cog into feenkcom/pullrequest3/vmmaker before we merge feenkcom/pullrequest3/vmmaker into OpenSmalltalk/Cog.

Its a big merge and merging first into you local repo allows you to better review the final result before doing the PR, and makes that PR a simple fast-forward merge.

Also I presumed this applies...
   https://stackoverflow.com/questions/12413745/pull-requests-for-orphan-branch
though I've not tested this in practice. YMMV

**Pull request closed without merging**
