### PR TITLE
Added X11 support for horizontal scroll wheel.

### PR DESCRIPTION
**Pull request by michael-roe**
Added X11 support for mice with a horizontal scroll wheel, such as Apple mice.

### CODE REVIEW

**Comment by michael-roe** [comment]
In the Pharo bug tracker, issue #4795 "Horizontal wheel events" explains why this fix will be problematic: control+left/right arrow are used for other purposes (moving by a word in the text editor), so we can't use this key combination to represent a scroll wheel event without breaking its other use as a shortcut in the text editor.

In the Mac OS virtual machine, fakeMouseWheelKeyboardEvents() in sqMacUIEvents.c has an #ifdef PharoVM to use control+option+command+shift+cursor key for mouse wheel events, avoiding the clash with the text editor's keyboard shortcut. We could do this in the Unix virtual machine as well.

**Comment by krono** [comment]
@eliotmiranda, any thoughts here? Otherwise, I'd just merge and see

**Comment by eliotmiranda** [comment]
No thoughts.  I’m not doing much work on Linux these days.  So I agree.  Let’s merge and see what happens.

**Comment by eliotmiranda** [comment]
and on iOS (the Cocoa Mac OS/iPhone platforms) the same approach is taken in fakeMouseWheelKeyboardEventsKeyCode:windowIndex:

    evt.modifiers = (CtrlKeyBit | OptionKeyBit | CommandKeyBit | ShiftKeyBit);

So I shall modify the X11 code to do the same.  And I shall comment the code.  These things NEED TO BE COMMENTED :-)

**Pull request merged**
