### PR TITLE
Pullrequest/vmmaker

### PR DESCRIPTION
**Pull request by eliotmiranda**
Initial pull request to include VMMaker source in opensmalltalk-vm repo.

Things that still need to be done before we can move to this version:
- provide access to the Smalltalk part of the repo (Tonel format) from Squeak.
- plugin source still needs to be included.

### CODE REVIEW

**Comment by nicolas-cellier-aka-nice** [comment]
Hi Eliot, great work!
It seems that history graph is flatten though.
This generates strange diffs for parallel branches.
Also a (Tonel?) bug flips compound category from Symbol to String _et vice et versa_, which generates spurious diffs...
Which tool did you use for the mc->git conversion?

**Comment by georgeganea** [comment]
Hi Nicolas,
We used  https://github.com/peteruhnak/git-migration. 
We selected the packages 
 #('Balloon-Engine-Pools' 'BytecodeSets.spur' 'VMMaker' 'VMMaker.oscog' 'Cog' 'CogTools' 'ImageFormat' 'VMMakerCompatibilityForPharo6' 'Android-Base' 'CMakeVMMaker' 'CMakeVMMakerSqueak' 'CogAttic' 'CogBenchmarks' 'CogCompatibility' 'CogTools-Listener' 'ImageFormat' 'MemoryAccess' 'Qwaq-VMProfiling' 'SlangBrowser' 'VMM-touch-temp' 'VMMakerCompatibilityForPharo6' 'VMMakerExtras' 'VMMakerJS'), and the migration tool just creates a long line of commits.

**Comment by georgeganea** [comment]
Could you please post an example for "strange diffs for parallel branches" and also for the "compound category from Symbol to String et vice et versa"?

**Comment by nicolas-cellier-aka-nice** [comment]
Example of String/Symbol mess: find the real changes in:

https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/4accb9e06df33a2326c0b2934cf15ac89edf3c06

Example of parallel branches mess:

This commit is a merge of VMMaker.oscog-nice.2109 and VMMaker.oscog-eem.2109, and thus should have 2 parents instead of one:
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/d5fae5a534a0c8b3eaa6b4756529aee3935e9dcd

Its parent is VMMaker.oscog-nice.2109
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/af7947fbea937adcc14aa979d39259e49e898ce1

and its parent has been marked incorrectly as VMMaker.oscog-eem.2109
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/a97aba90b29305784f37a1561726dbe94218fb2f

We thus see diffs between two different branches VMMaker.oscog-nice.2109 and VMMaker.oscog-eem.2109 which is completely irrelevant...

Also, it would be good to append the name of original Monticello package (and why not URL) at the end of the commit message for easing diagnostics!

**Comment by nicolas-cellier-aka-nice** [comment]
parallel branch problems is now https://github.com/peteruhnak/git-migration/issues/18

**Comment by georgeganea** [comment]
> parallel branch problems is now [peteruhnak/git-migration#18](https://github.com/peteruhnak/git-migration/issues/18)

Very cool!

**Comment by georgeganea** [comment]
I did https://github.com/pharo-vcs/tonel/pull/63.

**Comment by krono** [comment]
This looks a bit outdated, no?

**Pull request closed without merging**
