### PR TITLE
Do not use linux-latest runner, use an older stable version.

### PR DESCRIPTION
**Pull request by dtlewis290**
A VM compiled on ubuntu-20.04 (aka latest) will not run on
ubuntu-16.04 due to runtime library link issues. Therefore
select ubuntu-18.04 as a build runner that is likely to support
a wider range of existing Linux systems. Addresses this problem:

 /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### CODE REVIEW

**Comment by marceltaeumel** [comment]
Not sure how easy this will be. The error for FT2Plugin (pharo.cog.spur (itimer) for linux32x86 (ASSERT)) looks strange:
```
2021-09-25T15:45:21.6226488Z /bin/bash /home/runner/work/opensmalltalk-vm/opensmalltalk-vm/building/linux32x86/pharo.cog.spur/build.assert.itimerheartbeat/libtool --mode=link gcc -Wall  -g3 -O1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DDEBUGVM=0 -msse2 -DCOGMTVM=0 -DITIMER_HEARTBEAT=1 -pthread -DLSB_FIRST=1  -m32 -Wl,-rpath,'$ORIGIN'  -L/usr/local/lib -Wl,-z,now   -avoid-version -module -rpath /home/runner/work/opensmalltalk-vm/opensmalltalk-vm/products/assert/phphcogspur32linux/lib/squeak/`/home/runner/work/opensmalltalk-vm/opensmalltalk-vm/building/linux32x86/pharo.cog.spur/build.assert.itimerheartbeat/getversion VERSION_TAG` -o FT2Plugin.la FT2Plugin.lo  -lfreetype 
2021-09-25T15:45:21.7755681Z libtool: link: gcc -shared  -fPIC -DPIC  .libs/FT2Plugin.o   -L/usr/local/lib /usr/lib/x86_64-linux-gnu/libfreetype.so  -g3 -O1 -mno-omit-leaf-frame-pointer -msse2 -pthread -m32 -Wl,-rpath -Wl,\$ORIGIN -Wl,-z -Wl,now   -pthread -Wl,-soname -Wl,FT2Plugin.so -o .libs/FT2Plugin.so
2021-09-25T15:45:21.7821403Z /usr/lib/x86_64-linux-gnu/libfreetype.so: error adding symbols: File in wrong format
```
It tries to link a 64-bit library against the 32-bit binary.

This is how it is supposed to look:

```
2021-09-22T22:59:49.0624944Z /bin/bash /home/runner/work/opensmalltalk-vm/opensmalltalk-vm/building/linux32x86/pharo.cog.spur/build.assert.itimerheartbeat/libtool --mode=link gcc -Wall  -g3 -O1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DDEBUGVM=0 -msse2 -DCOGMTVM=0 -DITIMER_HEARTBEAT=1 -pthread -DLSB_FIRST=1  -m32 -Wl,-rpath,'$ORIGIN'  -L/usr/local/lib -Wl,-z,now   -avoid-version -module -rpath /home/runner/work/opensmalltalk-vm/opensmalltalk-vm/products/assert/phphcogspur32linux/lib/squeak/`/home/runner/work/opensmalltalk-vm/opensmalltalk-vm/building/linux32x86/pharo.cog.spur/build.assert.itimerheartbeat/getversion VERSION_TAG` -o FT2Plugin.la FT2Plugin.lo  -lfreetype 
2021-09-22T22:59:49.1511502Z libtool: link: gcc -shared  -fPIC -DPIC  .libs/FT2Plugin.o   -L/usr/local/lib -lfreetype  -g3 -O1 -mno-omit-leaf-frame-pointer -msse2 -pthread -m32 -Wl,-rpath -Wl,\$ORIGIN -Wl,-z -Wl,now   -pthread -Wl,-soname -Wl,FT2Plugin.so -o .libs/FT2Plugin.so
2021-09-22T22:59:49.1869202Z libtool: link: ( cd ".libs" && rm -f "FT2Plugin.la" && ln -s "../FT2Plugin.la" "FT2Plugin.la" )
2021-09-22T22:59:49.1898979Z : FT2Plugin.la
```

**Comment by marceltaeumel** [comment]
Ubuntu 18.04 does not make it easy for me.

First, I encountered a strange issue in `apt install` where dependency resolution for the 32-bit package `libpango1.0-dev:i386` did not work. I had to first check `libharfbuzz-dev:i386` and finally ` libicu-dev:i386` to make the pango library install as expected.

Second, `make configure` failed with a `error: possibly undefined macro: LT_LIB_DLLOAD`. I had to manually install `libltdl-dev` ... `libtool` was apparently not enough. See "scripts/ci/actions_prepare_linux_x86.sh" for the usual list.

<s>And finally, I cannot even build "squeak.cog.spur" for "linux64x64" because linking fails. It's again about the pango library:</s> Nevermind. Same package-loading issue as with the 32-bit packages. I had to install `libicu-dev` first to install `libpango1.0-dev`.

Not sure about that "autoconf" incident, but something fishy might be going on with pango in Ubuntu 18.04.

Update: No luck with building "linux32x86" either:

```
libtool: compile:  gcc -Wall -g -O2 -DNDEBUG -DDEBUGVM=0 -msse2 -DCOGMTVM=0 -pthread -DLSB_FIRST=1 -m32 -Wno-missing-braces -Wno-unknown-pragmas -Wno-unused-value -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -DHAVE_CONFIG_H -I/home/marcel/src/opensmalltalk-vm/building/linux32x86/squeak.cog.spur/build -I/home/marcel/src/opensmalltalk-vm/building/linux32x86/squeak.cog.spur/build -I/home/marcel/src/opensmalltalk-vm/platforms/unix/vm -I/home/marcel/src/opensmalltalk-vm/platforms/Cross/vm -I/home/marcel/src/opensmalltalk-vm/src/spur32.cog -I/usr/local/include -I/home/marcel/src/opensmalltalk-vm/platforms/Cross/plugins/UnicodePlugin -m32 -Wno-missing-braces -Wno-unknown-pragmas -Wno-unused-value -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -c /home/marcel/src/opensmalltalk-vm/platforms/unix/plugins/UnicodePlugin/UnicodeOps-linux.c  -fPIC -DPIC -o .libs/UnicodeOps-linux.o
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/pango-1.0/pango/pango-coverage.h:25,
                 from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/pango-1.0/pango/pangocairo.h:25,
                 from /home/marcel/src/opensmalltalk-vm/platforms/unix/plugins/UnicodePlugin/UnicodeOps-linux.c:28:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:241:53: error: size of array ‘_GStaticAssertCompileTimeAssertion_0’ is negative
```

**Comment by marceltaeumel** [comment]
I am now looking at the hardcoded magic in "platforms/unix/plugins/UnicodePlugin/acinclude.m4". Maybe this is the reason why the VM binaries did not play so well in the first place? Maybe we can use Ubuntu 20.04 after all?

**Comment by marceltaeumel** [comment]
Okay. We don't even build the "UnicodePlugin" in the CI because:
```
2021-09-22T23:04:54.3201231Z checking for PangoCairo libraries... no
2021-09-22T23:04:54.3202551Z ******** disabling UnicodePlugin
```

But in both Ubuntu 18.04 and 20.04, we have them loaded by default. Hmm.... anyway. Both "FT2Plugin" (Pharo only) and "UnicodePlugin" are currently not built in the CI with Ubuntu 20.04 but somehow here when using Ubuntu 18.04.

Next questions:
 - Why does the "UnicodePlugin" not build under 32-bit? Should it? (see "platforms/unix/plugins/UnicodePlugin/acinclude.m4")
 - Why does the CI using Ubuntu 20.04 not build the "UnicodePlugin" (and "FT2Plugin" for Pharo) even though Pango/Cairo is installed (see scripts/ci/actions_prepare_linux_x86.sh)?
 - What's the expected behavior? Should we build those plugins?

The configure check just tries to include "<pango/pangocairo.h" so I suspect an issue with the include path...

**Comment by dtlewis290** [comment]
With respect to UnicodePlugin, we may be seeing an interaction with some changes in PR#585, specifically the changes to UnicodePlugin/Makefile.inc and UnicodePlugin/acinclude.m4 (thanks Phil B for the pointer). Prior to merging PR#585, I had noticed that UnicodePlugin was failing for the 32-bit builds on my old Ubuntu 16.04 system. However, it built cleanly on the CI, so I chose to overlook that issue at the time. Now we see that UnicodePlugin build is failing on CI when we specify an Ubuntu 18.04 (not bleeding edge, not ancient, sort of middle of the road) build runner. This suggest that we need to look more carefully at the changes to those two files in https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/585/files#diff-722b7a283e9564d68e2f15142c6aa9e2ea1fba3e2c71ce87defc965fcdf02dcd

**Comment by pbella** [comment]
As @dtlewis290 suggests, I think it's reasonable to look at my 585 changes as being the culprit.  I changed Makefile.inc / acinclude.m4 to add _-I/usr/lib/x86_64-linux-gnu/glib-2.0/include_ when I saw that UnicodePlugin was failing to be configured on 64-bit Debian due to autoconf not finding a needed header.  This resolved the  issue on my Debian build VMs but these were not multiarch enabled (i.e. I had *either* a 32-bit or 64-bit build environment, not a combined one) so I suspect the problem might be with multiarch build environments having both 32-bit and 64-bit PangoCairo-related libraries installed at the same time?  If that's the case, one solution could be to have the 'build for platform' detection append the include path to only the appropriate /usr/lib/&lt;arch&gt;/glib-2.0/include directory rather than both which should eliminate any conflict on multiarch enabled systems.  If the issue isn't related to multiarch then I'm not sure what the cause is.

**Comment by krono** [comment]
Probably we should actually follow GLibs requirements and use `pkg-config`?
[This seems appropriate](https://stackoverflow.com/questions/1732822/portably-include-glib-headers-in-autoconf-automake):

> By using the `PKG_CHECK_MODULES` macro, Autoconf-generated configure scripts can retrieve pkg-config data automatically. […]
> ```
> PKG_CHECK_MODULES([DEPS], [glib-2.0 >= 2.24.1])
> ```

Or step by step: https://stackoverflow.com/a/14828132

However,  these all assume automake, but we dont use that. I'll have a look…

**Comment by krono** [comment]
(Actually, David's notes in the Readme seem pretty acurate)

**Comment by krono** [comment]
see ea296f0

**Comment by marceltaeumel** [comment]
Here is what we should check before merging:
 [x] linux32x86-squeak.cog.spur includes the UnicodePlugin
 [x] linux64x64-squeak.cog.spur includes the UnicodePlugin
 [x] linux32ARMv6-squeak.cog.spur includes the UnicodePlugin
 [x] linux64ARMv8-squeak.cog.spur includes the UnicodePlugin
 [x] linux32x86-pharo.cog.spur includes the FT2Plugin
 [x] linux64x64-pharo.cog.spur includes the FT2Plugin

**Comment by dtlewis290** [comment]
Confirming - the CI build artifact now runs successfully on my Ubuntu 16.04 LTS system. Previously the VM would fail due to link errors as originally reported. These VMs should now run on a wider range of existing Linux machines.

**Comment by marceltaeumel** [comment]
This is great news! So it's even "forward compatible" on 16.04? I will wait with the merge until the most recent upstream errors got fixed. Sigh... ☕

**Pull request merged**
