### PR TITLE
fixes on linux build for pharo + others

### PR DESCRIPTION
**Pull request by estebanlm**

### CODE REVIEW

**Comment by estebanlm** [comment]
so... this is very weird. Most of the modifications there actually are not mine, and they are already present on Cog branch. 
Does anyone knows why is showing it like this... and what can I do to fix it?

**Comment by bencoman** [comment]
If you look at the network chart (my favourite github feature), 
https://github.com/OpenSmalltalk/opensmalltalk-vm/network
on the far right (19-March) I can see estebanlm/Cog pulls in from OpenSmalltalk/Cog mainline.
Following your branch to the far left where it first branched off OpenSmalltalk/Cog (6-Feb)
I see the first commit of the branch is the first commit listed above.

Your pull request merges all the commits on that branch back into the mainline.
When you say "they are already present on Cog branch" that would seem to only your own Cog branch.  For example, picking the next commit on your branch (18 Feb).
ca2fc67 Removed builldbg and buildast from zip step
I don't see it in the log of the  OpenSmalltalk/Cog mainline.

On my local machine...
```
$ cd opensmaltalk-vm
$ git remote -v
opensmalltalk-vm	https://github.com/OpenSmalltalk/opensmalltalk-vm.git (fetch)
$ git fetch opensmalltalk-vm
$ git checkout opensmalltalk-vm/Cog
You are in 'detached HEAD' state. 
HEAD is now at 1f81775... CogVM source as per VMMaker.oscog-eem.2166
$ git log | grep buildbg
==>nothing
```

So is it confusion about which Cog branch is which?  
Perhaps this branch you normally work on should be called "pharo-vm" branch?

**Comment by estebanlm** [comment]
mmm... not sure I understand. I work on estebanlm/opensmalltalk-vm/Cog, and I keep it update with OpenSmalltalk/opensmalltalk-vm/Cog. 
Before doing a PR, I always merge with latest sources from OpenSmalltalk/opensmalltalk-vm/Cog, to keep the branch up-to-date. I really cannot understand why I have some changes that should not be there (because I pulled them from the branch against whom I made the PR). 

Now, even more weird: when I did the PR and wrote the first comment, I was seeing "257" files changed and that's why I was scared. Now it says 35 and looks a lot more reasonable (and those changes were the ones I did :P)

**Comment by bencoman** [comment]
You didn't provide a concrete example of "they are already present on Cog branch" or previously report the number (257) of changed files (so I did't pay attention to it) but maybe it was a glitch and I only saw the more-reasonable view. So my response was trying to fit a square peg into round hole.  Please ignore.

**Comment by estebanlm** [comment]
yeah, thanks for look at it! :)

**Comment by nicolas-cellier-aka-nice** [comment]
Hi Esteban, could I request a more continuous integration?
There are plenty of good things here, but now we'll have to merge with my work on building windows pharo VM (both 32 and 64 bits).

**Comment by estebanlm** [comment]
yes, of course... I usually do it faster, but last couple of months have been... hard :S 
can I merge this?

**Comment by nicolas-cellier-aka-nice** [comment]
OK, I'll merge the 2 requests

**Pull request merged**
