### PR TITLE
Customization for Pharo & About Dialog

### PR DESCRIPTION
**Pull request by tesonep**
- We added customization for Pharo to allow a different menu to be used. 
- We modified the default action of help menu to open an URL (only for Pharo)
- We added a Info.plist property with the string value of the URL (only for Pharo)

- And also the about dialog was not receiving the close event, we have fixed that. It was related with the filtering of events for SDL.

@demarey

### CODE REVIEW

**Comment by demarey** [comment]
fixes pharo-project/pharo#3036
fixes pharo-project/pharo-launcher#318

**Comment by bencoman** [comment]
Query though... why disable B3DAcceleratorPlugin ?
This is not mentioned anywhere in this PR.

**Comment by tesonep** [comment]
It is true, I have reverted that change. Sorry!

**Comment by bencoman** [comment]
No worries.  A fresh set of eyes is always useful.
Looks good to me now.

**Comment by eliotmiranda** [comment]
Hi Pablo,

    why not rewrite the Makefiles to use platforms/iOS/vm/English.lproj/$(SYSTEM)-MainMenu.xib?  This would match $(OSXDIR)/$(SYSTEM)-Info.plist and mean less files had to change.  We'd have to duplicate the MainMenu.xib files, one for Newspeak, Pharo and Squeak, but that's not much, and is in the pattern we already have.

**Comment by astares** [comment]
@tesonep ping

**Comment by nicolas-cellier-aka-nice** [comment]
Agree with Eliot, the changes are good, but would be better factored and generalized if we would 

1. change the `common/Makefile.app` to include the flavour specific menu `platforms/iOS/vm/English.lproj/$(SYSTEM)-MainMenu.xib`
2. and `mv platforms/iOS/vm/English.lproj/MainMenu.xib platforms/iOS/vm/English.lproj/Squeak-MainMenu.xib`
3. then `cp platforms/iOS/vm/English.lproj/Squeak-MainMenu.xib platforms/iOS/vm/English.lproj/Newspeak-MainMenu.xib`

**Comment by krono** [comment]
I'm inclined to close. Any takers otherwise?

**Comment by astares** [comment]
Still not solved - and customization should be allowed/possible. 

Otherwise people will not be able to build labeled products based on the VM.

**Comment by demarey** [comment]
I did a PR to update this one some days ago: https://github.com/tesonep/opensmalltalk-vm/pull/1
Waiting for merge

**Pull request merged**
