### PR TITLE
[Unix/Sockets] Fix Resolution of FQDNs >64 chars

### LINKED ISSUE #619: Cannot resolve domain names longer than 64 characters on linux
SocketPlugin uses a buffer of size MAXHOSTNAMELEN + 1 on [unix](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/6d38f13347be1031168b8b02e8ca52dc1b74be1c/platforms/unix/plugins/SocketPlugin/sqUnixSocket.c#L212).
The value of that constant is 64 on linux. A domain name can have up to 255 octets with each label having up to 63 octets.
So, 64 is definitely not the right value, nor is MAXHOSTNAMELEN, because the buffer is there to store a domain name, not a host name.

### PR DESCRIPTION
**Pull request by krono**
We used to use MAXHOSTNAMELEN, but that is 64 on most Linuxen and
might be differen w/ or w/o POSIX compliance. We now use the
definitions from and implications by DNS itself.

Now, we can

```
WebClient httpGet: 'http://theofficialabsolutelongestdomainnameregisteredontheworldwideweb.international/'
```

Fixes #619

### CODE REVIEW

**Comment by eliotmiranda** [comment]
The only change I would make would be to add a comment at the end of #define FQDN_LEN 253 to have it read
#define FQDN_LEN 253 // FullyQualifiedDomainName
or put it in the comment.  I had to think for a few seconds before I worked out what FQDN stood for.  Take away that pain :-)

**Comment by krono** [comment]
Sorry :D
I figure(d) that fqdn is a very well known concept around DNS.
Maybe it is sufficient to expand FQDn in the comment above it?

**Comment by eliotmiranda** [comment]
> On May 26, 2022, at 1:09 PM, Tobias Pape ***@***.***> wrote:
> 
> ﻿
> Sorry :D
> I figure(d) that fqdn is a very well known concept around DNS.
> Maybe it is sufficient to expand FQDn in the comment above it?
> 

Yes, that will work :-)

**Comment by philipschilling** [comment]
It's actually not directly related to this issue but if you need another long domain for testing, you can try [https://taumatawhakatangihanga.koauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu.nz](https://taumatawhakatangihanga.koauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu.nz)

Interestingly, the SSL certificates of my web provider also supported only 64 characters for the full domain but in some cases it can be much longer. The domain above has 89 characters.

**Pull request merged**
