### PR TITLE
21375-Add-FileAttributesPlugin-to-stack-and-lowcode-VMs

### PR DESCRIPTION
**Pull request by akgrant43**
Add FileAttributesPlugin to any remaining VM that already includes
FilePlugin.

### CODE REVIEW

**Comment by akgrant43** [comment]
The appveyor failure was a squeak build, which doesn't include FileAttributesPlugin, and looks like it was a failure to download cygwin related files.  This PR should be good to go...

**Comment by akgrant43** [comment]
Fogbugz: https://pharo.fogbugz.com/f/cases/21375/

**Comment by fniephaus** [comment]
> The appveyor failure was a squeak build, which doesn't include FileAttributesPlugin, and looks like it was a failure to download cygwin related files. This PR should be good to go...

Thanks for the info. I've fixed the problem that caused Pharo builds to fail on PRs in the meantime.

Merging this now, assuming @eliotmiranda and @estebanlm are ok with that...

**Comment by akgrant43** [comment]
> Merging this now, assuming @eliotmiranda and @estebanlm are ok with that...

Thanks @fniephaus !

I checked with @estebanlm before submitting the PR.

I didn't check with @eliotmiranda, but this doesn't change the VM, just the pharo build on some platforms, so hope that is OK.

**Pull request merged**
