### PR TITLE
Use the new files.pharo.org server to deploy Pharo VMs

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by clementbera** [comment]
It impacts only pharo deployment scripts. Merging.

**Comment by estebanlm** [comment]
meh :/ 
I was doing the same in branch estebanlm/fix-pharo-upload 
anyway, cool is done... now there are a problem in the build of libgit2 I guess due some dependencies?

**Comment by fniephaus** [comment]
I've just pushed https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/ec439f18e994309de62f64c23b48e35920633f39 with a fix for the libcurl/libgit2 issue.

**Comment by estebanlm** [comment]
> On 22 Dec 2017, at 14:49, Fabio Niephaus <notifications@github.com> wrote:
> 
> I've just pushed ec439f1 <https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/ec439f18e994309de62f64c23b48e35920633f39> with a fix for the libcurl/libgit2 issue.
> 
thanks :)

**Pull request merged**
