### PR TITLE
fix SqueakSSL plugin build for PharoVM macOS

### PR DESCRIPTION
**Pull request by estebanlm**
at least in high sierra this was failing

### CODE REVIEW

**Comment by krono** [comment]
What is openssl necessary for?

**Comment by estebanlm** [comment]
No idea, but SqueakSSL needs it. 
then, we need it too (for other stuff like ssh2 and libgit2, etc.)

**Comment by krono** [comment]
No, SqueakSSL on macOS does _not_ use openssl. In fact, the `-lssl -lcrypto` should be _removed_

**Comment by krono** [comment]
If you need openssl for ssh2 and libgit2, Ok, but SqueakSSL is not the place for that

**Comment by estebanlm** [comment]
ah well... it was like that (i didn't added the -lssl -lcrypto), and because of them it was failing the build. 
I just made sure compilation succeeds.

**Comment by krono** [comment]
Yeah, I see, not meant to blame you.
I think I'll just remove it directly in `Cog`, ok?

**Comment by eliotmiranda** [comment]
> On Jan 3, 2018, at 10:20 AM, Tobias Pape <notifications@github.com> wrote:
> 
> Yeah, I see, not meant to blame you.
> I think I'll just remove it directly in Cog, ok?
> 

Yes please :-)

**Comment by krono** [comment]
It has been done :D

**Comment by nicolas-cellier-aka-nice** [comment]
I presume that the changes for building openssl are still necessary (if openssl is used by some other libs).
Esteban, could you remove changes to platforms/iOS/plugins/SqueakSSL/Makefile and commit again?

**Comment by estebanlm** [comment]
yeah, on his way

**Comment by krono** [comment]
yay

**Pull request merged**
