### PR TITLE
serial: Remove unused variable holding a default filename

### PR DESCRIPTION
**Pull request by zecke**

### CODE REVIEW

**Comment by bencoman** [comment]
Its easy to confirm its unused... https://github.com/OpenSmalltalk/opensmalltalk-vm/search?q=serialPortBaseName&unscoped_q=serialPortBaseName

**Comment by krono** [comment]
That code is all over the place… `__APPLE`  ?!

**Comment by bencoman** [comment]
> That code is all over the place… __APPLE ?!
@krono, was that a response for me?  Yes `_APPLE` is all over,
but `serialPortBaseName` per url  `search?q=serialPortBaseName` is not.
Anyway I see you've merged it already. cheers.

**Comment by krono** [comment]
no, I meant the original one :)

**Pull request merged**
