### PR TITLE
increse fallback window size on Mac to a standard dimension

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/288

### CODE REVIEW

**Comment by krono** [comment]
how is  976 by 665 a “standard” dimension? that does not make sense

**Comment by pavel-krivanek** [comment]
just Pharo standard dimension of Pharo window... Squeak has 1024@768. Both are random values from the perspective of this PR.

**Comment by pavel-krivanek** [comment]
well, I updated the PR. I know from where 1024x768 comes from. That's why I wanted a smaller resolution since on displays with XGA resolution is the window too big because of window decorations etc. I meant that from the perspective of this PR the values are "random" magic numbers and it is not a proper solution. But better than nothing.

**Comment by pavel-krivanek** [comment]
Closing this PR. It does not solve the problem in the right place

**Pull request closed without merging**
